# Generated by Django 4.1 on 2023-03-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel1',
            name='bookdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
