# Generated by Django 4.1 on 2023-03-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmsapp', '0004_alter_uploadmodel1_bookdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel1',
            name='bookdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
