# Generated by Django 4.1 on 2023-03-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmsapp', '0006_uploaddisplaym_delete_uploadmodel1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddisplaym',
            name='uploaddate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
